namespace CNC.App.Workspace;

/// <summary>Assignable workspace panel identifiers.</summary>
public enum WorkspaceEditorId
{
    TabGroup,
    Program,
    Viewer3D,
    Console,
    Mdi,
    MdiTouch,
    Dro,
    ProgramLimits,
    Signals,
    Status,
    Jog,
    Outline,
    Goto,
    WorkParams,
    Spindle,
    SpindleTouch,
    Coolant,
    Feed,
    FeedTouch,
    JobBar,
    Macros,
    Keyboard,
    NumberPad,
    Probing,
    SdCard,
    Lathe,
    Offsets,
    Tools,
    GrblConfig,
    AppConfig,
}
